# Generated by Django 4.2.5 on 2023-09-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'admin'), (2, 'reader')], default=1),
        ),
    ]
