# Generated by Django 4.2.5 on 2023-09-16 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shopping_center', '0002_remove_pants_chat_with_admin_remove_pants_pants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Clothes/')),
                ('price', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=50)),
                ('about_shoes', models.TextField()),
                ('colour', models.CharField(default='', max_length=35)),
                ('size', models.SmallIntegerField()),
                ('year_created', models.DateField()),
                ('made_in_from', models.CharField(max_length=30)),
                ('if_sold', models.BooleanField(default=datetime.datetime.now)),
                ('for_which_season', models.CharField(default='', max_length=20)),
                ('Chat_with_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_center.shopping_center')),
            ],
            options={
                'db_table': 'Clothes',
            },
        ),
    ]
