# Generated by Django 4.2.5 on 2023-09-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='about_shoes',
            new_name='about_clothes',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='brand',
            new_name='clothes_brand',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='colour',
            new_name='clothes_colour',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='for_which_season',
            new_name='clothes_for_which_season',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='made_in_from',
            new_name='clothes_made_in_from',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='price',
            new_name='clothes_price',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='size',
            new_name='clothes_size',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='year_created',
            new_name='clothes_year_created',
        ),
    ]
