# Generated by Django 4.2.5 on 2023-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0003_alter_clothes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clothes_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
