# Generated by Django 4.2.5 on 2023-09-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sold_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sold_CPSH', models.CharField(default='', max_length=24)),
                ('sold_clothes', models.TextField()),
                ('sold_pants', models.TextField()),
                ('sold_shoes', models.TextField()),
            ],
        ),
    ]
