# Generated by Django 4.2.3 on 2023-10-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sold_Things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold_out',
            old_name='Sold_CPSH',
            new_name='sold_things',
        ),
    ]
