# Generated by Django 4.2.5 on 2023-09-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pants',
            old_name='about_shoes',
            new_name='about_pants',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='brand',
            new_name='pants_brand',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='colour',
            new_name='pants_colour',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='for_which_season',
            new_name='pants_for_which_season',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='made_in_from',
            new_name='pants_made_in_from',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='price',
            new_name='pants_price',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='size',
            new_name='pants_size',
        ),
        migrations.RenameField(
            model_name='pants',
            old_name='year_created',
            new_name='pants_year_created',
        ),
    ]
