# Generated by Django 4.2.5 on 2023-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pants', '0003_alter_pants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pants',
            name='pants_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
