# Generated by Django 4.2.5 on 2023-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pants', '0004_pants_pants_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pants',
            name='Chat_with_admin',
        ),
        migrations.AddField(
            model_name='pants',
            name='Contact_with_admin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
