# Generated by Django 4.2.5 on 2023-09-15 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_center_name', models.CharField(default='', max_length=50)),
                ('Shoes_SH', models.CharField(default='', max_length=50)),
                ('Clothes', models.CharField(default='', max_length=60)),
                ('Pants', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'Shopping_center',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Shoes/')),
                ('price', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=50)),
                ('about_shoes', models.TextField()),
                ('colour', models.CharField(default='', max_length=35)),
                ('size', models.SmallIntegerField()),
                ('year_created', models.DateField()),
                ('made_in_from', models.CharField(max_length=30)),
                ('if_sold', models.BooleanField(default=datetime.datetime.now)),
                ('for_which_season', models.CharField(default='', max_length=20)),
                ('Chat_with_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_center.shopping_center')),
            ],
            options={
                'db_table': 'Shoes',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Pants/')),
                ('price', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=50)),
                ('about_shoes', models.TextField()),
                ('colour', models.CharField(default='', max_length=35)),
                ('size', models.SmallIntegerField()),
                ('year_created', models.DateField()),
                ('made_in_from', models.CharField(max_length=30)),
                ('if_sold', models.BooleanField(default=datetime.datetime.now)),
                ('for_which_season', models.CharField(default='', max_length=20)),
                ('Chat_with_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_center.shopping_center')),
            ],
            options={
                'db_table': 'Pants',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Clothes/')),
                ('price', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=50)),
                ('about_shoes', models.TextField()),
                ('colour', models.CharField(default='', max_length=35)),
                ('size', models.SmallIntegerField()),
                ('year_created', models.DateField()),
                ('made_in_from', models.CharField(max_length=30)),
                ('if_sold', models.BooleanField(default=datetime.datetime.now)),
                ('for_which_season', models.CharField(default='', max_length=20)),
                ('Chat_with_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_center.shopping_center')),
            ],
            options={
                'db_table': 'Clothes',
            },
        ),
    ]
