# Generated by Django 4.2.5 on 2023-09-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pants',
            name='Chat_with_admin',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='pants',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Pants',
        ),
    ]
