# Generated by Django 4.2.5 on 2023-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_center', '0002_remove_pants_chat_with_admin_remove_pants_pants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='shoes_man/'),
        ),
    ]
