# Generated by Django 4.2.5 on 2023-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_center', '0003_alter_shoes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_center',
            name='shopping_center_name',
            field=models.CharField(max_length=50),
        ),
    ]
