# Generated by Django 4.2.5 on 2023-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_center', '0004_alter_shopping_center_shopping_center_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='shoes_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='shopping_center',
            name='shopping_center_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
